server:
  port: 8080

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

  jwt:
    secret-key: ${JWT_SECRET}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}
    access-expiration: ${JWT_ACCESS_EXPIRATION}

  config:
    import: optional:dotenv


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

resilience4j:
  circuitbreaker:
    instances:
      ebookService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      ebookService:
        maxAttempts: 3
        waitDuration: 2s
